[package]
name = "glim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arboard = { version = "3.4.0", default-features = false, features = ["windows-sys", "wl-clipboard-rs"] }
chrono = { version = "0.4.37", features = ["serde"] }
colorsys = "0.6.7"
confy = "0.6.1"
crossterm = "0.27.0"
derive_builder = "0.20.0"
directories = "5.0.1"
itertools = "0.12.1"
once_cell = "1.19.0"
open = "5.1.2"
rand = { version = "0.8.5", features = ["small_rng"] }
ratatui = "0.26.1"
reqwest = "0.12.3"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
thiserror = "1.0.61"
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }
tui-input = "0.8.0"
